### ISSUE TITLE
No devices visible

### ISSUE THREAD

**Issue by lukevredeveld** [FilipDem/Domoticz-iROBOT-ROOMBA-plugin#2]
Followed everything in the readme. All steps seem to work, but no devices are created in Domoticz. Hardware is visible though...
Any ideas?

/edit: it seems now the mqtt_Roomba.py script doesn't work like it should. Devices are visible, Domoticz blocked new devices, but that's ok now.

It gives this output:

```
pi@raspberrypi:~/domoticz/plugins/Roomba $ python3 mqtt_Roomba.py -D 3

CV or numpy module not found, falling back to PIL
PIL module not found, maps are disabled

Error: [Errno 111] Connection refused
Attempting new Connection# 1
Error: [Errno 111] Connection refused

Attempting new Connection# 2
Error: [Errno 111] Connection refused

Attempting new Connection# 3
Error: [Errno 111] Connection refused

Unable to connect
Broker disconnected
```

**Comment by FilipDem** [comment]
MQTT Client cannot connect to the ROOMBA... So probably a network issue...
Do you have the right IP address (check your config.ini file)? Be sure (when using DHCP) that the IP address does not change (put it as "fixed" in your router). You could try to PING the ROOMBA with the IP address.
Be sure that also the necessary ports are not blocked at your router...

**Comment by lukevredeveld** [comment]
It worked briefly, but now I have got the same problem. The roomba is online, ping averages 20ms. It shows itself in domoticz (the 'seen last time' keeps updating throughout the day) but it doesn't change state when the robot actually runs. Also, the robot cannot start from the domoticz control panel

**Comment by lukevredeveld** [comment]
So, i put the hardware in debug-mode in domoticz, and tried the switch. There is nothing I can work with here I'm afraid...

```
13:21:17.443 (Stoffie) Heartbeating...

2021-01-22 13:21:17.443 (Stoffie) MqttClient::Ping

**2021-01-22 13:21:24.657 (Stoffie) Command: On (1) Color:

2021-01-22 13:21:24.657 (Stoffie) MqttClient::Publish /roomba/command (dock)

2021-01-22 13:21:24.647 Status: User: Admin (IP: 192.168.1.126) initiated a switch command (1093/Stoffie - Run/On)**

2021-01-22 13:21:27.415 (Stoffie) Heartbeating...

2021-01-22 13:21:27.416 (Stoffie) MqttClient::Ping

2021-01-22 13:21:37.436 (Stoffie) Heartbeating...

2021-01-22 13:21:37.436 (Stoffie) MqttClient::Ping

2021-01-22 13:21:47.456 (Stoffie) Heartbeating...
```

**Comment by FilipDem** [comment]
In my opinion, there is still sth with the communication. Others seems to have integrated it without problem (see message of `manuloup` on https://www.domoticz.com/forum/viewtopic.php?p=266595#p266595 dd 19/01/2021): 

> No problem Filip. Just wanted to give you my return because I followed the procedure.
> Anyway, that is a good job and the plugin is working well. Thanks for all.
> 

mqtt_Roomba.py connects to the ROOMBA and publishes (MQTT PUB) ROOMBA data to the mosquitto (MQTT brooker). The domoticz plugin (plugin.py) is the MQTT client/subscriber. 

Check if mosquitto is really running. All is based on 'localhost' so be sure it is running on the same machine as your domoticz. You can check it with `sudo service mosquitto status`. I suppose it will be the case seen the domoticz client can connect (otherwise I would have seen an error message in the log). I am rather sure it is between the ROOMBA and domoticz. 

Be sure that mqtt_Roomba.py is also running. If you start it manually, be sure that at every reboot it is started. If you created a service (as indicated in the procedure, check if the service is running with `sudo service roomba status`.

You can test without domoticz by starting a MQTT subscriber manually. If you run `mosquitto_sub -v -t /roomba/feedback/#` (again on the same machine), you should receive the raw output that is sent regularly by ROOMBA. Output should be something like:

```
/roomba/feedback/netinfo_dhcp True
/roomba/feedback/netinfo_addr 3232261301
/roomba/feedback/netinfo_mask 4294967040
/roomba/feedback/netinfo_gw 3232261121
/roomba/feedback/netinfo_dns1 3232261121
/roomba/feedback/netinfo_dns2 0
/roomba/feedback/netinfo_bssid 6c:b0:ce:14:2f:cd
/roomba/feedback/netinfo_sec 4
/roomba/feedback/wifistat_wifi 1
/roomba/feedback/wifistat_uap False
/roomba/feedback/wifistat_cloud 1
/roomba/feedback/netinfo_dhcp True
... (deleted a part)
/roomba/feedback/bbsys_hr 517
/roomba/feedback/bbsys_min 57
/roomba/feedback/state Charging
/roomba/feedback/signal_rssi -35
/roomba/feedback/signal_snr 54
/roomba/feedback/state Charging
/roomba/feedback/signal_rssi -36
/roomba/feedback/signal_snr 53
/roomba/feedback/state Charging
```
If you don't have this, it will certainly not work in Domoticz.
Hope it helps. Success

**Comment by lukevredeveld** [comment]
each time after a day flawless operation, it stopped working. So I checked (again) if the roomba service was running:

pi@raspberrypi:~/domoticz/plugins/Roomba $ sudo service roomba status

● roomba.service - Roomba mqtt client
   Loaded: loaded (/etc/systemd/system/roomba.service; **disabled**; vendor preset: 
   Active: active (running) since Fri 2021-01-22 13:32:53 CET; 2 days ago
 Main PID: 835 (python3)
    Tasks: 1 (limit: 2063)
   CGroup: /system.slice/roomba.service
           └─835 /usr/bin/python3 /home/pi/domoticz/plugins/Roomba/mqtt_Roomba.p

Jan 22 13:32:53 raspberrypi systemd[1]: Started Roomba mqtt client.
Jan 23 **06:02:44** raspberrypi python3[835]: Unexpected Disconnect From Roomba ! - 
Jan 23 06:02:44 raspberrypi python3[835]: Unexpected Disconnect From Roomba ! - 
Jan 23 08:35:21 raspberrypi python3[835]: Error looking up Roomba error message 


If I manually restart the service with `sudo service roomba restart` it works for another day.
Just now, I noticed the timestamp in the above output. My main router restarts every morning at 6AM. It's a 'leftover' from some problems with repeaters last year. So now, I have cancelled the daily reboot of the main router. Let's see if that helps :-)

**Comment by FilipDem** [comment]
Normally the problem with network connections or rebooting the router should be solved with the new commits. You can find the instructions in paragraph "Updating from mqtt_Roomba.py to roomba module (linux)". Shortly I made it a bit more easier by using directly the roomba module instead of the mqtt_Roomba.py. With the new version you can remove this file.
I tested it by rebooting my rooter, blacklisting for a long time the MAC address of the roomba, ... everything went back to normal.
Hope this helps! And if you are happy with the plugin an support, small contributions are always welcome.

**Comment by lukevredeveld** [comment]
still no go I'm afraid. Tried on two different pi's: one pi were the previous version was installed. I first tried the upgrade step. That didn't work. After that I cleaned all the files and re-installed the plugin. Again: no luck. I get error 111 all the times. After that, I used a new pi 4, with only domoticz installed. Same problem, same error... I'm giving up...

● roomba.service - Roomba mqtt client
   Loaded: loaded (/etc/systemd/system/roomba.service; disabled; vendor preset: enabled)
   Active: active (running) since Sun 2021-01-31 20:09:10 CET; 2s ago
 Main PID: 804 (python3)
    Tasks: 1 (limit: 3861)
   CGroup: /system.slice/roomba.service
           └─804 /usr/bin/python3 /home/pi/domoticz/plugins/Roomba/roomba --configfile /home/pi/domotic

Jan 31 20:09:10 raspberrypi python3[804]: [I 2021-01-31 20:09:10,872] <CNTRL C> to Exit
Jan 31 20:09:10 raspberrypi python3[804]: [I 2021-01-31 20:09:10,872] Roomba 980 MQTT data Interface
Jan 31 20:09:10 raspberrypi python3[804]: [I 2021-01-31 20:09:10,875] reading info from config file /ho
Jan 31 20:09:10 raspberrypi python3[804]: [I 2021-01-31 20:09:10,877] connecting to broker
Jan 31 20:09:10 raspberrypi python3[804]: [I 2021-01-31 20:09:10,883] Creating Roomba object 192.168.1.
Jan 31 20:09:10 raspberrypi python3[804]: [I 2021-01-31 20:09:10,884] connecting Roomba 192.168.1.197
Jan 31 20:09:11 raspberrypi python3[804]: Error: [Errno 111] Connection refused
Jan 31 20:09:11 raspberrypi python3[804]: Attempting new Connection to Roomba (#1)
Jan 31 20:09:12 raspberrypi python3[804]: Error: [Errno 111] Connection refused
Jan 31 20:09:12 raspberrypi python3[804]: Attempting new Connection to Roomba (#2)
